# Generated by Django 5.0.14 on 2025-05-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisit",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pagevisit",
            name="page",
            field=models.CharField(max_length=255),
        ),
    ]
