# Generated by Django 5.0.14 on 2025-05-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0002_pagevisit_path_alter_pagevisit_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagevisit",
            name="page",
        ),
    ]
